version: "3"
services:
  php8-tips-tricks:
    container_name: php8_tips
    hostname: server1
    image: php8tips/php8_tips_image
    volumes:
     - .:/repo
    ports:
     - 8888:80
    build: .
    restart: always
    command: lfphp --mysql --apache --phpfpm
    networks:
      app_net:
        ipv4_address: 172.16.0.22

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/24"
